# Generated by Django 4.1 on 2022-10-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('like', models.DecimalField(decimal_places=0, max_digits=5)),
                ('share', models.DecimalField(decimal_places=0, max_digits=5)),
                ('title', models.CharField(max_length=255)),
                ('article_post', models.TextField()),
            ],
        ),
    ]
