# Generated by Django 4.1 on 2022-10-29 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_exactdate_article_exactmonth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='exactdate',
        ),
        migrations.RemoveField(
            model_name='article',
            name='exactmonth',
        ),
    ]
