# Generated by Django 4.1 on 2022-10-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_user_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='artid',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
