# Generated by Django 4.1 on 2022-10-28 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calorycalc', '0005_alter_caloryinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloryinfo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
