# Generated by Django 4.1 on 2022-10-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorycalc', '0006_alter_caloryinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloryinfo',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
