# Generated by Django 4.1 on 2022-10-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorycalc', '0007_alter_caloryinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloryinfo',
            name='calory',
            field=models.IntegerField(default=0),
        ),
    ]
