# Generated by Django 4.1 on 2022-11-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorycalc', '0008_alter_caloryinfo_calory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloryinfo',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
