# Generated by Django 4.1 on 2022-11-02 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorycalc', '0009_alter_caloryinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloryinfo',
            name='calory',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
