# Generated by Django 4.1 on 2022-10-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('calories', models.IntegerField(blank=True, default=0, null=True)),
                ('protein', models.IntegerField(blank=True, default=0, null=True)),
                ('fat', models.IntegerField(blank=True, default=0, null=True)),
                ('carbs', models.IntegerField(blank=True, default=0, null=True)),
                ('is_food', models.BooleanField(blank=True, default=True, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
