# Generated by Django 4.1 on 2022-12-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_rec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='user',
        ),
    ]
