# Generated by Django 4.1 on 2022-11-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='username',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
