# Generated by Django 4.1 on 2022-11-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0002_testimony_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='username',
        ),
    ]
